theme = "bogster"

[editor]
line-number = "relative"
bufferline = "multiple"
rulers = [80]
true-color = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":write" # Ctrl and 's' to write

C-e = ["align_view_bottom", "move_line_down" ]
C-y = ["align_view_top", "move_line_up" ]

[keys.normal.Z]

Q = ":q!"
Z = ":wq"


[keys.normal."รง"]
q = ":reflow"

[editor.cursor-shape]
insert = "bar"
