[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]

[[language]]
name = "typst"
language-servers = ["tinymist", "harper-ls"]


[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
